import type { VocabWord } from "../types";

export const businessVocab: VocabWord[] = [
  // meetings (会议)
  {
    id: "biz-w-001",
    track: "business",
    topic: "meetings",
    headword: "action item",
    ipa: "/ˈækʃn ˌaɪtəm/",
    pos: "n.",
    definitionEn: "A specific task assigned to someone after a meeting.",
    translationZh: "行动事项；待办任务",
    exampleEn: "Let's list the action items and assign an owner to each one.",
    exampleZh: "我们把行动事项列出来，并为每一项指定负责人。",
  },
  {
    id: "biz-w-002",
    track: "business",
    topic: "meetings",
    headword: "adjourn",
    ipa: "/əˈdʒɜːrn/",
    pos: "v.",
    definitionEn: "To end a meeting formally, often until a later time.",
    translationZh: "休会；散会",
    exampleEn: "The chairperson adjourned the meeting until nine o'clock the next morning.",
    exampleZh: "主席宣布休会，会议将于次日上午九点继续。",
  },
  {
    id: "biz-w-003",
    track: "business",
    topic: "meetings",
    headword: "minutes",
    ipa: "/ˈmɪnɪts/",
    pos: "n.",
    definitionEn: "The official written record of what was said at a meeting.",
    translationZh: "会议记录",
    exampleEn: "Sarah will circulate the minutes to all attendees by the end of the day.",
    exampleZh: "莎拉会在今天下班前把会议记录发给所有与会者。",
  },
  {
    id: "biz-w-004",
    track: "business",
    topic: "meetings",
    headword: "consensus",
    ipa: "/kənˈsensəs/",
    pos: "n.",
    definitionEn: "General agreement among the members of a group.",
    translationZh: "共识",
    exampleEn: "After a long discussion, the board reached a consensus on the new pricing strategy.",
    exampleZh: "经过长时间讨论，董事会就新定价策略达成了共识。",
  },
  {
    id: "biz-w-005",
    track: "business",
    topic: "meetings",
    headword: "brainstorm",
    ipa: "/ˈbreɪnstɔːrm/",
    pos: "v.",
    definitionEn: "To suggest many ideas quickly in a group discussion.",
    translationZh: "头脑风暴",
    exampleEn: "The team met on Friday to brainstorm ideas for the product launch.",
    exampleZh: "团队周五开会，为产品发布进行头脑风暴。",
  },
  {
    id: "biz-w-006",
    track: "business",
    topic: "meetings",
    headword: "circle back",
    ipa: "/ˌsɜːrkl ˈbæk/",
    pos: "phr.",
    definitionEn: "To return to a topic or person later.",
    translationZh: "回头再谈；稍后再议",
    exampleEn: "We're short on time, so let's circle back to this issue next week.",
    exampleZh: "时间不够了，这个问题我们下周再回头讨论。",
  },
  {
    id: "biz-w-007",
    track: "business",
    topic: "meetings",
    headword: "touch base",
    ipa: "/ˌtʌtʃ ˈbeɪs/",
    pos: "phr.",
    definitionEn: "To make brief contact with someone to exchange updates.",
    translationZh: "简短沟通；碰头",
    exampleEn: "Let's touch base on Thursday to review the project's progress.",
    exampleZh: "我们周四碰个头，一起看看项目进展。",
  },
  {
    id: "biz-w-008",
    track: "business",
    topic: "meetings",
    headword: "wrap up",
    ipa: "/ˌræp ˈʌp/",
    pos: "phr.",
    definitionEn: "To finish or conclude something, such as a meeting.",
    translationZh: "结束；收尾",
    exampleEn: "Before we wrap up, does anyone have questions about the timeline?",
    exampleZh: "在结束之前，大家对时间安排还有什么问题吗？",
  },
  {
    id: "biz-w-009",
    track: "business",
    topic: "meetings",
    headword: "facilitate",
    ipa: "/fəˈsɪlɪteɪt/",
    pos: "v.",
    definitionEn: "To guide a meeting or process so it runs smoothly.",
    translationZh: "主持；推动",
    exampleEn: "An outside consultant was brought in to facilitate the strategy workshop.",
    exampleZh: "公司请来一位外部顾问来主持战略研讨会。",
  },
  {
    id: "biz-w-010",
    track: "business",
    topic: "meetings",
    headword: "takeaway",
    ipa: "/ˈteɪkəweɪ/",
    pos: "n.",
    definitionEn: "A key point or lesson to remember from a discussion.",
    translationZh: "要点；心得",
    exampleEn: "The main takeaway from today's meeting is that we need faster customer feedback.",
    exampleZh: "今天会议的主要结论是我们需要更快获得客户反馈。",
  },
  // negotiation (谈判)
  {
    id: "biz-w-011",
    track: "business",
    topic: "negotiation",
    headword: "leverage",
    ipa: "/ˈlevərɪdʒ/",
    pos: "n.",
    definitionEn: "Power or advantage used to influence a negotiation.",
    translationZh: "筹码；影响力",
    exampleEn: "Being the supplier's largest customer gives us considerable leverage in price talks.",
    exampleZh: "作为该供应商最大的客户，我们在价格谈判中拥有相当大的筹码。",
  },
  {
    id: "biz-w-012",
    track: "business",
    topic: "negotiation",
    headword: "concession",
    ipa: "/kənˈseʃn/",
    pos: "n.",
    definitionEn: "Something you give up in order to reach an agreement.",
    translationZh: "让步",
    exampleEn: "We made a concession on delivery times in exchange for a lower price.",
    exampleZh: "我们在交货时间上做了让步，以换取更低的价格。",
  },
  {
    id: "biz-w-013",
    track: "business",
    topic: "negotiation",
    headword: "counteroffer",
    ipa: "/ˈkaʊntərɔːfər/",
    pos: "n.",
    definitionEn: "An offer made in response to another offer that was unacceptable.",
    translationZh: "还盘；还价",
    exampleEn: "The vendor rejected our bid and returned with a higher counteroffer.",
    exampleZh: "供应商拒绝了我们的报价，并提出了更高的还盘。",
  },
  {
    id: "biz-w-014",
    track: "business",
    topic: "negotiation",
    headword: "trade-off",
    ipa: "/ˈtreɪd ɔːf/",
    pos: "n.",
    definitionEn: "A balance between two things you cannot have both of.",
    translationZh: "权衡；取舍",
    exampleEn: "There is always a trade-off between product quality and production cost.",
    exampleZh: "产品质量与生产成本之间总要有所取舍。",
  },
  {
    id: "biz-w-015",
    track: "business",
    topic: "negotiation",
    headword: "bottom line",
    ipa: "/ˌbɑːtəm ˈlaɪn/",
    pos: "n.",
    definitionEn: "The lowest price or final position someone will accept; net profit.",
    translationZh: "底线；净利润",
    exampleEn: "Our bottom line is fifty dollars per unit; we cannot go any lower.",
    exampleZh: "我们的底线是每件五十美元，不能再低了。",
  },
  {
    id: "biz-w-016",
    track: "business",
    topic: "negotiation",
    headword: "compromise",
    ipa: "/ˈkɑːmprəmaɪz/",
    pos: "n.",
    definitionEn: "An agreement reached when each side gives up part of its demands.",
    translationZh: "妥协；折中方案",
    exampleEn: "After two days of talks, both sides accepted a reasonable compromise.",
    exampleZh: "经过两天的谈判，双方接受了一个合理的折中方案。",
  },
  {
    id: "biz-w-017",
    track: "business",
    topic: "negotiation",
    headword: "deal-breaker",
    ipa: "/ˈdiːl breɪkər/",
    pos: "n.",
    definitionEn: "An issue serious enough to end a negotiation.",
    translationZh: "致命问题；无法接受的条件",
    exampleEn: "The lack of a warranty clause proved to be a deal-breaker for the buyer.",
    exampleZh: "缺少保修条款最终让买方放弃了这笔交易。",
  },
  {
    id: "biz-w-018",
    track: "business",
    topic: "negotiation",
    headword: "middle ground",
    ipa: "/ˌmɪdl ˈɡraʊnd/",
    pos: "n.",
    definitionEn: "A position acceptable to both sides in a disagreement.",
    translationZh: "折中立场；中间地带",
    exampleEn: "The two teams eventually found a middle ground on the licensing fees.",
    exampleZh: "双方最终在许可费用问题上找到了折中方案。",
  },
  {
    id: "biz-w-019",
    track: "business",
    topic: "negotiation",
    headword: "hammer out",
    ipa: "/ˌhæmər ˈaʊt/",
    pos: "phr.",
    definitionEn: "To reach an agreement after long or difficult discussion.",
    translationZh: "敲定；反复商定",
    exampleEn: "Lawyers from both companies hammered out the final terms overnight.",
    exampleZh: "两家公司的律师连夜敲定了最终条款。",
  },
  {
    id: "biz-w-020",
    track: "business",
    topic: "negotiation",
    headword: "win-win",
    ipa: "/ˌwɪn ˈwɪn/",
    pos: "adj.",
    definitionEn: "Describing a result that benefits everyone involved.",
    translationZh: "双赢的",
    exampleEn: "The partnership is a win-win arrangement that expands both companies' markets.",
    exampleZh: "这一合作是双赢安排，扩大了两家公司的市场。",
  },
  // email (邮件)
  {
    id: "biz-w-021",
    track: "business",
    topic: "email",
    headword: "follow up",
    ipa: "/ˌfɑːloʊ ˈʌp/",
    pos: "phr.",
    definitionEn: "To take further action or check progress after an earlier contact.",
    translationZh: "跟进",
    exampleEn: "I will follow up with the client if we hear nothing by Friday.",
    exampleZh: "如果周五前还没有回音，我会跟进联系客户。",
  },
  {
    id: "biz-w-022",
    track: "business",
    topic: "email",
    headword: "attachment",
    ipa: "/əˈtætʃmənt/",
    pos: "n.",
    definitionEn: "A file sent together with an email.",
    translationZh: "附件",
    exampleEn: "Please review the attachment and send me your comments by Wednesday.",
    exampleZh: "请查看附件，并在周三前把意见发给我。",
  },
  {
    id: "biz-w-023",
    track: "business",
    topic: "email",
    headword: "loop in",
    ipa: "/ˌluːp ˈɪn/",
    pos: "phr.",
    definitionEn: "To include someone in an email conversation or discussion.",
    translationZh: "拉入讨论；抄送知会",
    exampleEn: "I'm looping in our legal team so they can review the terms.",
    exampleZh: "我把法务团队加进来，以便他们审核这些条款。",
  },
  {
    id: "biz-w-024",
    track: "business",
    topic: "email",
    headword: "acknowledge",
    ipa: "/əkˈnɑːlɪdʒ/",
    pos: "v.",
    definitionEn: "To confirm that you have received or noticed something.",
    translationZh: "确认收到",
    exampleEn: "Please acknowledge receipt of this email so we know the file arrived.",
    exampleZh: "请确认收到此邮件，以便我们知道文件已送达。",
  },
  {
    id: "biz-w-025",
    track: "business",
    topic: "email",
    headword: "recipient",
    ipa: "/rɪˈsɪpiənt/",
    pos: "n.",
    definitionEn: "A person who receives something, such as an email or payment.",
    translationZh: "收件人",
    exampleEn: "Double-check the recipient list before sending the contract to avoid data leaks.",
    exampleZh: "发送合同前请再次核对收件人列表，以防信息泄露。",
  },
  {
    id: "biz-w-026",
    track: "business",
    topic: "email",
    headword: "reach out",
    ipa: "/ˌriːtʃ ˈaʊt/",
    pos: "phr.",
    definitionEn: "To contact someone, especially to offer or request help.",
    translationZh: "联系；主动接洽",
    exampleEn: "Feel free to reach out if you have any questions about the proposal.",
    exampleZh: "如对提案有任何疑问，请随时与我联系。",
  },
  {
    id: "biz-w-027",
    track: "business",
    topic: "email",
    headword: "escalate",
    ipa: "/ˈeskəleɪt/",
    pos: "v.",
    definitionEn: "To pass a problem to a higher level for attention.",
    translationZh: "上报；升级处理",
    exampleEn: "If the server issue continues, we will escalate it to senior management.",
    exampleZh: "如果服务器问题持续存在，我们将上报给高层管理者。",
  },
  {
    id: "biz-w-028",
    track: "business",
    topic: "email",
    headword: "clarify",
    ipa: "/ˈklærəfaɪ/",
    pos: "v.",
    definitionEn: "To make something easier to understand by explaining it.",
    translationZh: "澄清；说明",
    exampleEn: "Could you clarify the payment terms mentioned in your last email?",
    exampleZh: "你能澄清一下上封邮件中提到的付款条件吗？",
  },
  {
    id: "biz-w-029",
    track: "business",
    topic: "email",
    headword: "gentle reminder",
    ipa: "/ˌdʒentl rɪˈmaɪndər/",
    pos: "phr.",
    definitionEn: "A polite message reminding someone to do something.",
    translationZh: "温馨提醒；委婉催促",
    exampleEn: "Just a gentle reminder that the survey closes this Friday afternoon.",
    exampleZh: "温馨提醒：问卷调查将于本周五下午截止。",
  },
  {
    id: "biz-w-030",
    track: "business",
    topic: "email",
    headword: "at your earliest convenience",
    ipa: "/ət jʊr ˌɜːrliəst kənˈviːniəns/",
    pos: "phr.",
    definitionEn: "As soon as it is possible for you.",
    translationZh: "尽早；方便时尽快",
    exampleEn: "Please sign and return the agreement at your earliest convenience.",
    exampleZh: "请您方便时尽早签署并寄回协议。",
  },
  // presentations (演示汇报)
  {
    id: "biz-w-031",
    track: "business",
    topic: "presentations",
    headword: "slide deck",
    ipa: "/ˈslaɪd dek/",
    pos: "n.",
    definitionEn: "A set of presentation slides.",
    translationZh: "演示文稿；幻灯片",
    exampleEn: "I'll share the slide deck with everyone right after the presentation.",
    exampleZh: "演示结束后我会立刻把幻灯片分享给大家。",
  },
  {
    id: "biz-w-032",
    track: "business",
    topic: "presentations",
    headword: "walk through",
    ipa: "/ˌwɔːk ˈθruː/",
    pos: "phr.",
    definitionEn: "To explain something step by step.",
    translationZh: "逐步讲解",
    exampleEn: "Let me walk through the quarterly numbers before we discuss next steps.",
    exampleZh: "在讨论后续安排之前，我先逐项讲解季度数据。",
  },
  {
    id: "biz-w-033",
    track: "business",
    topic: "presentations",
    headword: "highlight",
    ipa: "/ˈhaɪlaɪt/",
    pos: "v.",
    definitionEn: "To emphasize the most important parts of something.",
    translationZh: "强调；突出",
    exampleEn: "The report highlights three areas where costs can be reduced immediately.",
    exampleZh: "报告重点指出了三个可以立即削减成本的领域。",
  },
  {
    id: "biz-w-034",
    track: "business",
    topic: "presentations",
    headword: "recap",
    ipa: "/ˈriːkæp/",
    pos: "v.",
    definitionEn: "To repeat the main points of something briefly.",
    translationZh: "概括；回顾",
    exampleEn: "To recap, we agreed on the budget, the timeline, and the team structure.",
    exampleZh: "简要回顾一下：我们就预算、时间表和团队结构达成了一致。",
  },
  {
    id: "biz-w-035",
    track: "business",
    topic: "presentations",
    headword: "drill down",
    ipa: "/ˌdrɪl ˈdaʊn/",
    pos: "phr.",
    definitionEn: "To examine something in greater detail.",
    translationZh: "深入分析",
    exampleEn: "Let's drill down into the regional sales figures to find the problem.",
    exampleZh: "我们深入分析各地区的销售数据，找出问题所在。",
  },
  {
    id: "biz-w-036",
    track: "business",
    topic: "presentations",
    headword: "handout",
    ipa: "/ˈhændaʊt/",
    pos: "n.",
    definitionEn: "A printed document given to people at a presentation.",
    translationZh: "讲义；发放材料",
    exampleEn: "The full financial tables are in the handout on your desks.",
    exampleZh: "完整的财务报表在各位桌上的讲义里。",
  },
  {
    id: "biz-w-037",
    track: "business",
    topic: "presentations",
    headword: "articulate",
    ipa: "/ɑːrˈtɪkjuleɪt/",
    pos: "v.",
    definitionEn: "To express ideas clearly in words.",
    translationZh: "清晰表达",
    exampleEn: "A good presenter can articulate complex ideas in simple language.",
    exampleZh: "优秀的演讲者能用简单的语言清晰表达复杂的观点。",
  },
  {
    id: "biz-w-038",
    track: "business",
    topic: "presentations",
    headword: "illustrate",
    ipa: "/ˈɪləstreɪt/",
    pos: "v.",
    definitionEn: "To explain something by giving examples or using pictures.",
    translationZh: "举例说明；图示",
    exampleEn: "She used a customer case study to illustrate the product's value.",
    exampleZh: "她用一个客户案例来说明产品的价值。",
  },
  {
    id: "biz-w-039",
    track: "business",
    topic: "presentations",
    headword: "pitch",
    ipa: "/pɪtʃ/",
    pos: "n.",
    definitionEn: "A short talk intended to persuade people to buy or invest.",
    translationZh: "推介；路演",
    exampleEn: "The startup delivered a five-minute pitch to a room full of investors.",
    exampleZh: "这家初创公司向满屋的投资人做了五分钟的路演。",
  },
  {
    id: "biz-w-040",
    track: "business",
    topic: "presentations",
    headword: "engage",
    ipa: "/ɪnˈɡeɪdʒ/",
    pos: "v.",
    definitionEn: "To attract and hold someone's interest and attention.",
    translationZh: "吸引；调动参与",
    exampleEn: "Asking questions early is a simple way to engage your audience.",
    exampleZh: "尽早提问是吸引听众参与的一个简单方法。",
  },
  // strategy (战略运营)
  {
    id: "biz-w-041",
    track: "business",
    topic: "strategy",
    headword: "stakeholder",
    ipa: "/ˈsteɪkhoʊldər/",
    pos: "n.",
    definitionEn: "A person or group with an interest in a business decision.",
    translationZh: "利益相关方",
    exampleEn: "We must consult all key stakeholders before changing the product roadmap.",
    exampleZh: "在调整产品路线图之前，我们必须征询所有关键利益相关方的意见。",
  },
  {
    id: "biz-w-042",
    track: "business",
    topic: "strategy",
    headword: "streamline",
    ipa: "/ˈstriːmlaɪn/",
    pos: "v.",
    definitionEn: "To make a process simpler and more efficient.",
    translationZh: "精简；优化流程",
    exampleEn: "The new software will streamline the approval process from days to hours.",
    exampleZh: "新软件将把审批流程从几天精简到几个小时。",
  },
  {
    id: "biz-w-043",
    track: "business",
    topic: "strategy",
    headword: "deliverable",
    ipa: "/dɪˈlɪvərəbl/",
    pos: "n.",
    definitionEn: "A product or result that must be completed and handed over.",
    translationZh: "交付成果",
    exampleEn: "The contract lists each deliverable along with its deadline and owner.",
    exampleZh: "合同列明了每项交付成果及其截止日期和负责人。",
  },
  {
    id: "biz-w-044",
    track: "business",
    topic: "strategy",
    headword: "benchmark",
    ipa: "/ˈbentʃmɑːrk/",
    pos: "n.",
    definitionEn: "A standard used to compare and measure performance.",
    translationZh: "基准；标杆",
    exampleEn: "We use industry benchmarks to evaluate our customer service performance.",
    exampleZh: "我们以行业基准来评估自身的客户服务表现。",
  },
  {
    id: "biz-w-045",
    track: "business",
    topic: "strategy",
    headword: "scale up",
    ipa: "/ˌskeɪl ˈʌp/",
    pos: "phr.",
    definitionEn: "To increase the size or capacity of a business or activity.",
    translationZh: "扩大规模",
    exampleEn: "The company plans to scale up production to meet growing overseas demand.",
    exampleZh: "公司计划扩大生产规模，以满足不断增长的海外需求。",
  },
  {
    id: "biz-w-046",
    track: "business",
    topic: "strategy",
    headword: "synergy",
    ipa: "/ˈsɪnərdʒi/",
    pos: "n.",
    definitionEn: "Extra value created when two organizations or teams work together.",
    translationZh: "协同效应",
    exampleEn: "The merger is expected to create significant synergy between the two sales networks.",
    exampleZh: "此次合并预计将在两个销售网络之间产生显著的协同效应。",
  },
  {
    id: "biz-w-047",
    track: "business",
    topic: "strategy",
    headword: "roadmap",
    ipa: "/ˈroʊdmæp/",
    pos: "n.",
    definitionEn: "A plan showing the stages of a project over time.",
    translationZh: "路线图；规划",
    exampleEn: "The product roadmap shows two major releases planned for next year.",
    exampleZh: "产品路线图显示明年计划发布两个重要版本。",
  },
  {
    id: "biz-w-048",
    track: "business",
    topic: "strategy",
    headword: "core competency",
    ipa: "/ˌkɔːr ˈkɑːmpɪtənsi/",
    pos: "n.",
    definitionEn: "A company's main strength that gives it a competitive advantage.",
    translationZh: "核心竞争力",
    exampleEn: "Fast, reliable delivery has become the retailer's core competency.",
    exampleZh: "快速可靠的配送已成为这家零售商的核心竞争力。",
  },
  {
    id: "biz-w-049",
    track: "business",
    topic: "strategy",
    headword: "milestone",
    ipa: "/ˈmaɪlstoʊn/",
    pos: "n.",
    definitionEn: "An important stage or event in the development of something.",
    translationZh: "里程碑",
    exampleEn: "Reaching one million users was a major milestone for the platform.",
    exampleZh: "用户数突破一百万是该平台的一个重要里程碑。",
  },
  {
    id: "biz-w-050",
    track: "business",
    topic: "strategy",
    headword: "outsource",
    ipa: "/ˈaʊtsɔːrs/",
    pos: "v.",
    definitionEn: "To pay another company to do work for your business.",
    translationZh: "外包",
    exampleEn: "The firm decided to outsource its customer support to reduce operating costs.",
    exampleZh: "该公司决定将客服外包，以降低运营成本。",
  },
];
