import type { VocabWord } from "../types";

export const ieltsVocab: VocabWord[] = [
  // environment (环境)
  {
    id: "ielts-w-001",
    track: "ielts",
    topic: "environment",
    headword: "mitigate",
    ipa: "/ˈmɪtɪɡeɪt/",
    pos: "v.",
    definitionEn: "To make something harmful less severe or serious.",
    translationZh: "缓解；减轻",
    exampleEn:
      "Governments are investing in flood defenses to mitigate the effects of climate change.",
    exampleZh: "各国政府正投资防洪设施，以减轻气候变化的影响。",
  },
  {
    id: "ielts-w-002",
    track: "ielts",
    topic: "environment",
    headword: "emission",
    ipa: "/ɪˈmɪʃn/",
    pos: "n.",
    definitionEn: "Gas or other substance released into the air.",
    translationZh: "排放（物）",
    exampleEn: "The new regulations aim to cut carbon emissions from factories by half.",
    exampleZh: "新法规旨在将工厂的碳排放量削减一半。",
  },
  {
    id: "ielts-w-003",
    track: "ielts",
    topic: "environment",
    headword: "deforestation",
    ipa: "/ˌdiːˌfɔːrɪˈsteɪʃn/",
    pos: "n.",
    definitionEn: "The cutting down of forests over a large area.",
    translationZh: "毁林；滥伐森林",
    exampleEn: "Deforestation in tropical regions has accelerated the loss of rare species.",
    exampleZh: "热带地区的滥伐森林加速了珍稀物种的消失。",
  },
  {
    id: "ielts-w-004",
    track: "ielts",
    topic: "environment",
    headword: "renewable",
    ipa: "/rɪˈnuːəbl/",
    pos: "adj.",
    definitionEn: "Naturally replaced and never used up, such as wind or solar energy.",
    translationZh: "可再生的",
    exampleEn: "Renewable sources now generate a third of the country's electricity.",
    exampleZh: "可再生能源目前提供了该国三分之一的电力。",
  },
  {
    id: "ielts-w-005",
    track: "ielts",
    topic: "environment",
    headword: "contaminate",
    ipa: "/kənˈtæmɪneɪt/",
    pos: "v.",
    definitionEn: "To make something impure or harmful by adding dangerous substances.",
    translationZh: "污染",
    exampleEn: "Chemical waste from the plant contaminated the river and nearby farmland.",
    exampleZh: "工厂排放的化学废料污染了河流和附近的农田。",
  },
  {
    id: "ielts-w-006",
    track: "ielts",
    topic: "environment",
    headword: "biodiversity",
    ipa: "/ˌbaɪoʊdaɪˈvɜːrsəti/",
    pos: "n.",
    definitionEn: "The variety of plant and animal life in an area.",
    translationZh: "生物多样性",
    exampleEn: "Protecting wetlands is essential for maintaining biodiversity in coastal regions.",
    exampleZh: "保护湿地对维持沿海地区的生物多样性至关重要。",
  },
  {
    id: "ielts-w-007",
    track: "ielts",
    topic: "environment",
    headword: "deplete",
    ipa: "/dɪˈpliːt/",
    pos: "v.",
    definitionEn: "To greatly reduce the amount of something.",
    translationZh: "耗尽；使枯竭",
    exampleEn: "Overfishing has severely depleted fish stocks in many parts of the ocean.",
    exampleZh: "过度捕捞已使海洋许多海域的鱼类资源严重枯竭。",
  },
  {
    id: "ielts-w-008",
    track: "ielts",
    topic: "environment",
    headword: "sustainable",
    ipa: "/səˈsteɪnəbl/",
    pos: "adj.",
    definitionEn: "Able to continue without harming the environment or exhausting resources.",
    translationZh: "可持续的",
    exampleEn: "The city is promoting sustainable transport by expanding its cycling network.",
    exampleZh: "该市正通过扩建自行车道网络来推广可持续交通。",
  },
  {
    id: "ielts-w-009",
    track: "ielts",
    topic: "environment",
    headword: "habitat",
    ipa: "/ˈhæbɪtæt/",
    pos: "n.",
    definitionEn: "The natural home of a plant or animal.",
    translationZh: "栖息地",
    exampleEn: "Urban expansion continues to destroy the natural habitat of many bird species.",
    exampleZh: "城市扩张不断破坏许多鸟类的自然栖息地。",
  },
  {
    id: "ielts-w-010",
    track: "ielts",
    topic: "environment",
    headword: "carbon footprint",
    ipa: "/ˌkɑːrbən ˈfʊtprɪnt/",
    pos: "n.",
    definitionEn:
      "The amount of carbon dioxide produced by a person's or organization's activities.",
    translationZh: "碳足迹",
    exampleEn:
      "Companies can reduce their carbon footprint by encouraging employees to work remotely.",
    exampleZh: "企业可以通过鼓励员工远程办公来减少碳足迹。",
  },
  // education (教育)
  {
    id: "ielts-w-011",
    track: "ielts",
    topic: "education",
    headword: "curriculum",
    ipa: "/kəˈrɪkjələm/",
    pos: "n.",
    definitionEn: "The subjects taught at a school or university.",
    translationZh: "课程体系",
    exampleEn: "Many universities have added data science to their standard curriculum.",
    exampleZh: "许多大学已将数据科学纳入其标准课程体系。",
  },
  {
    id: "ielts-w-012",
    track: "ielts",
    topic: "education",
    headword: "literacy",
    ipa: "/ˈlɪtərəsi/",
    pos: "n.",
    definitionEn: "The ability to read and write.",
    translationZh: "读写能力；识字率",
    exampleEn: "Improving adult literacy remains a priority in many developing countries.",
    exampleZh: "提高成人识字率仍是许多发展中国家的优先任务。",
  },
  {
    id: "ielts-w-013",
    track: "ielts",
    topic: "education",
    headword: "tuition",
    ipa: "/tuˈɪʃn/",
    pos: "n.",
    definitionEn: "Money paid for being taught, especially at a college or university.",
    translationZh: "学费",
    exampleEn: "Rising tuition fees have discouraged some students from attending university.",
    exampleZh: "不断上涨的学费使一些学生放弃了上大学。",
  },
  {
    id: "ielts-w-014",
    track: "ielts",
    topic: "education",
    headword: "compulsory",
    ipa: "/kəmˈpʌlsəri/",
    pos: "adj.",
    definitionEn: "Required by law or rules; must be done.",
    translationZh: "义务的；强制的",
    exampleEn: "In most countries, education is compulsory until the age of sixteen.",
    exampleZh: "在大多数国家，教育在十六岁之前是义务性的。",
  },
  {
    id: "ielts-w-015",
    track: "ielts",
    topic: "education",
    headword: "vocational",
    ipa: "/voʊˈkeɪʃənl/",
    pos: "adj.",
    definitionEn: "Relating to skills and training needed for a particular job.",
    translationZh: "职业的；职业技能的",
    exampleEn: "Vocational courses give students practical skills that employers value highly.",
    exampleZh: "职业课程能让学生掌握雇主非常看重的实用技能。",
  },
  {
    id: "ielts-w-016",
    track: "ielts",
    topic: "education",
    headword: "enroll",
    ipa: "/ɪnˈroʊl/",
    pos: "v.",
    definitionEn: "To officially register as a member of a course or school.",
    translationZh: "注册；入学",
    exampleEn:
      "A record number of international students enrolled in the engineering program this year.",
    exampleZh: "今年注册工程专业的国际学生人数创下新高。",
  },
  {
    id: "ielts-w-017",
    track: "ielts",
    topic: "education",
    headword: "assessment",
    ipa: "/əˈsesmənt/",
    pos: "n.",
    definitionEn: "The process of judging the quality of students' work or ability.",
    translationZh: "评估；考核",
    exampleEn: "Continuous assessment gives a fairer picture of ability than a single exam.",
    exampleZh: "持续性评估比一次考试更能公平地反映学生能力。",
  },
  {
    id: "ielts-w-018",
    track: "ielts",
    topic: "education",
    headword: "extracurricular",
    ipa: "/ˌekstrəkəˈrɪkjələr/",
    pos: "adj.",
    definitionEn: "Outside the normal course of study at a school.",
    translationZh: "课外的",
    exampleEn: "Extracurricular activities help students develop teamwork and leadership skills.",
    exampleZh: "课外活动有助于学生培养团队合作与领导能力。",
  },
  {
    id: "ielts-w-019",
    track: "ielts",
    topic: "education",
    headword: "pedagogy",
    ipa: "/ˈpedəɡɑːdʒi/",
    pos: "n.",
    definitionEn: "The method and practice of teaching.",
    translationZh: "教学法",
    exampleEn: "Modern pedagogy encourages discussion rather than passive memorization of facts.",
    exampleZh: "现代教学法提倡讨论，而非被动地死记硬背。",
  },
  {
    id: "ielts-w-020",
    track: "ielts",
    topic: "education",
    headword: "discipline",
    ipa: "/ˈdɪsəplɪn/",
    pos: "n.",
    definitionEn: "Training people to obey rules; also a subject of study.",
    translationZh: "纪律；学科",
    exampleEn: "Strict classroom discipline does not necessarily lead to better academic results.",
    exampleZh: "严格的课堂纪律未必能带来更好的学业成绩。",
  },
  // technology (科技)
  {
    id: "ielts-w-021",
    track: "ielts",
    topic: "technology",
    headword: "innovation",
    ipa: "/ˌɪnəˈveɪʃn/",
    pos: "n.",
    definitionEn: "A new idea, method, or invention.",
    translationZh: "创新",
    exampleEn:
      "Technological innovation has transformed the way companies communicate with customers.",
    exampleZh: "技术创新改变了企业与客户沟通的方式。",
  },
  {
    id: "ielts-w-022",
    track: "ielts",
    topic: "technology",
    headword: "automation",
    ipa: "/ˌɔːtəˈmeɪʃn/",
    pos: "n.",
    definitionEn: "The use of machines to do work previously done by people.",
    translationZh: "自动化",
    exampleEn: "Automation has replaced thousands of routine jobs in the manufacturing sector.",
    exampleZh: "自动化已取代了制造业数以千计的常规岗位。",
  },
  {
    id: "ielts-w-023",
    track: "ielts",
    topic: "technology",
    headword: "obsolete",
    ipa: "/ˌɑːbsəˈliːt/",
    pos: "adj.",
    definitionEn: "No longer used because something newer exists.",
    translationZh: "过时的；淘汰的",
    exampleEn: "Many experts predict that cash will become obsolete within a few decades.",
    exampleZh: "许多专家预测，现金将在几十年内被淘汰。",
  },
  {
    id: "ielts-w-024",
    track: "ielts",
    topic: "technology",
    headword: "cutting-edge",
    ipa: "/ˌkʌtɪŋ ˈedʒ/",
    pos: "adj.",
    definitionEn: "Extremely modern and advanced.",
    translationZh: "尖端的；前沿的",
    exampleEn: "The laboratory uses cutting-edge equipment to analyze genetic data.",
    exampleZh: "该实验室使用尖端设备来分析基因数据。",
  },
  {
    id: "ielts-w-025",
    track: "ielts",
    topic: "technology",
    headword: "breakthrough",
    ipa: "/ˈbreɪkθruː/",
    pos: "n.",
    definitionEn: "An important discovery or development.",
    translationZh: "突破",
    exampleEn: "The breakthrough in battery technology could make electric cars far cheaper.",
    exampleZh: "电池技术的突破可能使电动汽车便宜得多。",
  },
  {
    id: "ielts-w-026",
    track: "ielts",
    topic: "technology",
    headword: "algorithm",
    ipa: "/ˈælɡərɪðəm/",
    pos: "n.",
    definitionEn: "A set of rules a computer follows to solve a problem.",
    translationZh: "算法",
    exampleEn: "Social media algorithms decide which content each user sees first.",
    exampleZh: "社交媒体算法决定每个用户最先看到哪些内容。",
  },
  {
    id: "ielts-w-027",
    track: "ielts",
    topic: "technology",
    headword: "surveillance",
    ipa: "/sɜːrˈveɪləns/",
    pos: "n.",
    definitionEn: "The careful watching of people, especially by governments or technology.",
    translationZh: "监控；监视",
    exampleEn: "The growth of facial recognition has raised concerns about mass surveillance.",
    exampleZh: "人脸识别的普及引发了人们对大规模监控的担忧。",
  },
  {
    id: "ielts-w-028",
    track: "ielts",
    topic: "technology",
    headword: "connectivity",
    ipa: "/ˌkɑːnekˈtɪvəti/",
    pos: "n.",
    definitionEn: "The state of being connected, especially to the internet.",
    translationZh: "连通性；网络连接",
    exampleEn: "Poor internet connectivity still limits online education in rural areas.",
    exampleZh: "网络连接不佳仍然制约着农村地区的在线教育。",
  },
  {
    id: "ielts-w-029",
    track: "ielts",
    topic: "technology",
    headword: "artificial intelligence",
    ipa: "/ˌɑːrtɪfɪʃl ɪnˈtelɪdʒəns/",
    pos: "n.",
    definitionEn: "Computer systems that can perform tasks normally requiring human intelligence.",
    translationZh: "人工智能",
    exampleEn:
      "Artificial intelligence is increasingly used to diagnose diseases at an early stage.",
    exampleZh: "人工智能正越来越多地用于疾病的早期诊断。",
  },
  {
    id: "ielts-w-030",
    track: "ielts",
    topic: "technology",
    headword: "digitize",
    ipa: "/ˈdɪdʒɪtaɪz/",
    pos: "v.",
    definitionEn: "To convert information into a digital form computers can process.",
    translationZh: "数字化",
    exampleEn: "The national library plans to digitize millions of historical documents.",
    exampleZh: "国家图书馆计划将数百万份历史文献数字化。",
  },
  // society (社会)
  {
    id: "ielts-w-031",
    track: "ielts",
    topic: "society",
    headword: "demographic",
    ipa: "/ˌdeməˈɡræfɪk/",
    pos: "adj.",
    definitionEn: "Relating to the structure of a population.",
    translationZh: "人口的；人口统计的",
    exampleEn: "Demographic changes such as aging populations put pressure on healthcare systems.",
    exampleZh: "人口老龄化等人口结构变化给医疗体系带来压力。",
  },
  {
    id: "ielts-w-032",
    track: "ielts",
    topic: "society",
    headword: "urbanization",
    ipa: "/ˌɜːrbənəˈzeɪʃn/",
    pos: "n.",
    definitionEn: "The growth of cities as people move from rural areas.",
    translationZh: "城市化",
    exampleEn:
      "Rapid urbanization has created severe housing shortages in many developing countries.",
    exampleZh: "快速城市化在许多发展中国家造成了严重的住房短缺。",
  },
  {
    id: "ielts-w-033",
    track: "ielts",
    topic: "society",
    headword: "inequality",
    ipa: "/ˌɪnɪˈkwɑːləti/",
    pos: "n.",
    definitionEn: "An unfair situation where some people have more opportunities or money.",
    translationZh: "不平等",
    exampleEn: "Income inequality has widened despite decades of steady economic growth.",
    exampleZh: "尽管经济持续增长了数十年，收入不平等却在扩大。",
  },
  {
    id: "ielts-w-034",
    track: "ielts",
    topic: "society",
    headword: "welfare",
    ipa: "/ˈwelfer/",
    pos: "n.",
    definitionEn: "Help given by the state to people in need; well-being.",
    translationZh: "福利",
    exampleEn: "The government increased welfare spending to support unemployed workers.",
    exampleZh: "政府增加了福利开支以扶助失业人员。",
  },
  {
    id: "ielts-w-035",
    track: "ielts",
    topic: "society",
    headword: "migration",
    ipa: "/maɪˈɡreɪʃn/",
    pos: "n.",
    definitionEn: "The movement of people from one place to live in another.",
    translationZh: "移民；迁移",
    exampleEn:
      "Economic pressures have driven large-scale migration from rural villages to cities.",
    exampleZh: "经济压力促使人们大规模从农村迁往城市。",
  },
  {
    id: "ielts-w-036",
    track: "ielts",
    topic: "society",
    headword: "disparity",
    ipa: "/dɪˈspærəti/",
    pos: "n.",
    definitionEn: "A great and unfair difference between people or things.",
    translationZh: "差距；悬殊",
    exampleEn:
      "There is a clear disparity in educational resources between urban and rural schools.",
    exampleZh: "城乡学校之间的教育资源存在明显差距。",
  },
  {
    id: "ielts-w-037",
    track: "ielts",
    topic: "society",
    headword: "consumerism",
    ipa: "/kənˈsuːmərɪzəm/",
    pos: "n.",
    definitionEn: "The belief that buying more goods is desirable; high consumption.",
    translationZh: "消费主义",
    exampleEn: "Critics argue that consumerism encourages waste and damages the environment.",
    exampleZh: "批评者认为消费主义助长浪费并破坏环境。",
  },
  {
    id: "ielts-w-038",
    track: "ielts",
    topic: "society",
    headword: "infrastructure",
    ipa: "/ˈɪnfrəstrʌktʃər/",
    pos: "n.",
    definitionEn: "Basic systems such as roads, power, and communications that a country needs.",
    translationZh: "基础设施",
    exampleEn: "Investment in public infrastructure creates jobs and supports long-term growth.",
    exampleZh: "对公共基础设施的投资能创造就业并支撑长期增长。",
  },
  {
    id: "ielts-w-039",
    track: "ielts",
    topic: "society",
    headword: "cohesion",
    ipa: "/koʊˈhiːʒn/",
    pos: "n.",
    definitionEn: "The state of a group staying united and working together.",
    translationZh: "凝聚力",
    exampleEn:
      "Community festivals strengthen social cohesion among residents of different backgrounds.",
    exampleZh: "社区节庆活动增强了不同背景居民之间的社会凝聚力。",
  },
  {
    id: "ielts-w-040",
    track: "ielts",
    topic: "society",
    headword: "unprecedented",
    ipa: "/ʌnˈpresɪdentɪd/",
    pos: "adj.",
    definitionEn: "Never having happened or existed before.",
    translationZh: "史无前例的",
    exampleEn: "The pandemic caused an unprecedented shift toward online learning worldwide.",
    exampleZh: "疫情引发了全球范围内向在线学习的空前转变。",
  },
  // research (学术研究)
  {
    id: "ielts-w-041",
    track: "ielts",
    topic: "research",
    headword: "hypothesis",
    ipa: "/haɪˈpɑːθəsɪs/",
    pos: "n.",
    definitionEn: "An idea that is tested through study and experiment.",
    translationZh: "假设；假说",
    exampleEn: "The experiment was designed to test the hypothesis that sleep improves memory.",
    exampleZh: "该实验旨在检验睡眠能改善记忆这一假设。",
  },
  {
    id: "ielts-w-042",
    track: "ielts",
    topic: "research",
    headword: "empirical",
    ipa: "/ɪmˈpɪrɪkl/",
    pos: "adj.",
    definitionEn: "Based on observation or experiment rather than theory.",
    translationZh: "实证的；经验的",
    exampleEn: "There is little empirical evidence to support this widely held belief.",
    exampleZh: "几乎没有实证证据支持这一普遍看法。",
  },
  {
    id: "ielts-w-043",
    track: "ielts",
    topic: "research",
    headword: "methodology",
    ipa: "/ˌmeθəˈdɑːlədʒi/",
    pos: "n.",
    definitionEn: "The set of methods used in a particular study or activity.",
    translationZh: "方法论；研究方法",
    exampleEn: "The paper describes the methodology used to collect and analyze the survey data.",
    exampleZh: "该论文阐述了收集和分析调查数据所采用的研究方法。",
  },
  {
    id: "ielts-w-044",
    track: "ielts",
    topic: "research",
    headword: "variable",
    ipa: "/ˈveriəbl/",
    pos: "n.",
    definitionEn: "A factor in an experiment that can change or be changed.",
    translationZh: "变量",
    exampleEn: "Researchers controlled every variable except the amount of daily exercise.",
    exampleZh: "研究人员控制了除每日运动量之外的所有变量。",
  },
  {
    id: "ielts-w-045",
    track: "ielts",
    topic: "research",
    headword: "correlation",
    ipa: "/ˌkɔːrəˈleɪʃn/",
    pos: "n.",
    definitionEn: "A connection between two things in which one affects the other.",
    translationZh: "相关性",
    exampleEn:
      "The study found a strong correlation between reading habits and academic performance.",
    exampleZh: "研究发现阅读习惯与学业成绩之间存在很强的相关性。",
  },
  {
    id: "ielts-w-046",
    track: "ielts",
    topic: "research",
    headword: "qualitative",
    ipa: "/ˈkwɑːlɪteɪtɪv/",
    pos: "adj.",
    definitionEn: "Relating to descriptions and qualities rather than numbers.",
    translationZh: "定性的",
    exampleEn:
      "The team conducted qualitative interviews to understand students' attitudes toward homework.",
    exampleZh: "研究团队通过定性访谈了解学生对家庭作业的态度。",
  },
  {
    id: "ielts-w-047",
    track: "ielts",
    topic: "research",
    headword: "quantitative",
    ipa: "/ˈkwɑːntɪteɪtɪv/",
    pos: "adj.",
    definitionEn: "Relating to numbers and measurable amounts.",
    translationZh: "定量的",
    exampleEn:
      "Quantitative data from two thousand questionnaires supported the researchers' conclusions.",
    exampleZh: "来自两千份问卷的定量数据支持了研究人员的结论。",
  },
  {
    id: "ielts-w-048",
    track: "ielts",
    topic: "research",
    headword: "phenomenon",
    ipa: "/fəˈnɑːmɪnən/",
    pos: "n.",
    definitionEn: "Something that happens or exists and can be observed.",
    translationZh: "现象",
    exampleEn: "Urban heat islands are a well-documented phenomenon in large modern cities.",
    exampleZh: "城市热岛是大型现代城市中记录详实的一种现象。",
  },
  {
    id: "ielts-w-049",
    track: "ielts",
    topic: "research",
    headword: "bias",
    ipa: "/ˈbaɪəs/",
    pos: "n.",
    definitionEn: "An unfair preference that influences judgment or results.",
    translationZh: "偏见；偏差",
    exampleEn: "A small sample size can introduce serious bias into research findings.",
    exampleZh: "样本量过小可能给研究结果带来严重偏差。",
  },
  {
    id: "ielts-w-050",
    track: "ielts",
    topic: "research",
    headword: "peer review",
    ipa: "/ˌpɪr rɪˈvjuː/",
    pos: "n.",
    definitionEn: "The evaluation of academic work by other experts in the field.",
    translationZh: "同行评审",
    exampleEn: "The findings were published only after a rigorous peer review process.",
    exampleZh: "这些研究结果经过严格的同行评审后才得以发表。",
  },
];
