import { businessListening } from "./listening/business";
import { ieltsListening } from "./listening/ielts";
import { toeicListening } from "./listening/toeic";
import { businessReading } from "./reading/business";
import { ieltsReading } from "./reading/ielts";
import { toeicReading } from "./reading/toeic";
import { businessSpeaking } from "./speaking/business";
import { ieltsSpeaking } from "./speaking/ielts";
import { toeicSpeaking } from "./speaking/toeic";
import { businessVocab } from "./vocab/business";
import { ieltsVocab } from "./vocab/ielts";
import { toeicVocab } from "./vocab/toeic";
import { businessWriting } from "./writing/business";
import { ieltsWriting } from "./writing/ielts";
import { toeicWriting } from "./writing/toeic";
import { ieltsMiniExam } from "./exams/ielts-mini";
import { toeicMiniExam } from "./exams/toeic-mini";

export const allVocab = [...toeicVocab, ...ieltsVocab, ...businessVocab];
export const allReading = [...toeicReading, ...ieltsReading, ...businessReading];
export const allListening = [...toeicListening, ...ieltsListening, ...businessListening];
export const allWriting = [...toeicWriting, ...ieltsWriting, ...businessWriting];
export const allSpeaking = [...toeicSpeaking, ...ieltsSpeaking, ...businessSpeaking];
export const allExams = [toeicMiniExam, ieltsMiniExam];
